### PR TITLE
Feature/bump botorch

### PR DESCRIPTION
**Pull request by jduerholt**
This PR bumps the botorch version to 0.9.1 and the minimal required python version to 3.9.0.

### CODE REVIEW

**Comment by bertiqwerty** [comment]
What about first a new BoFire release with BoTorch<0.9 and then bumping BoTorch such that we have a pip-installable BoFire-version that works with Python 3.8. Ubuntu LTS 20.4 is still supported and has Python 3.8 as default Python.

**Comment by jduerholt** [comment]
Let us discuss this in our next meeting, I want to have indeed a release soon ;)

**Comment by jduerholt** [comment]
I just merge it in as we have already agreed on this.

**Comment by bertiqwerty** [comment]
Sorry. Forgot to click the approve button.

**Pull request merged**
