### PR TITLE
[Lint] apply ruff format as all safe fixes

### PR DESCRIPTION
**Pull request by CompRhys**
Apply some formatting to the code, apply ruff safe fixes, use codespell to identify and fix 80% of typos in the code

### CODE REVIEW

**Comment by CompRhys** [comment]
@jduerholt I think the remaining test error here is unrelated as is also see on other open PRs

**Comment by jduerholt** [comment]
Thanks, I will also remove these tests. I think they are in general not needed anymore. @bertiqwerty : could you also have a look?

**Review by bertiqwerty — APPROVED** [review]
Thanks.

**Review by jduerholt — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by jduerholt** [comment]
@CompRhys : thank you. Could you solve the merge conflicts? It should be done relatively easily. I think the only problem is the change in the enums. Best, Johannes

**Comment by CompRhys** [comment]
done, I just accepted all incoming changes in the merge

**Pull request merged**
