### PR TITLE
Revert "Doe categorical"

### PR DESCRIPTION
**Pull request by ufukguenes**
Reverts experimental-design/bofire#243

### CODE REVIEW

**Comment by jduerholt** [comment]
Hi @ufukguenes,

thank you very much for reverting. I hope this is fine for you, But I want to have the pyright stuff fixed before merging in and have some discussion on the additional features.

Sorry for this!

Best,

Johannes

**Comment by dlinzner-bcs** [comment]
@jduerholt we are ready to revert. Can you please check if those failed tests are expected?

**Comment by jduerholt** [comment]
> @jduerholt we are ready to revert. Can you please check if those failed tests are expected?

Yep, they are expected, they sometimes fail and sometimes pass as the surrogate is fitted to random data which creates sometimes problems. This needs to be fixed on the long run.

**Comment by dlinzner-bcs** [comment]
No worries. I am always confused about the importance of pyright running through :D as for the additional types I agree that this is up to discussion. Thank you for protecting our project <3

**Pull request merged**
