### PR TITLE
Feature/trim pipeline

### PR DESCRIPTION
**Pull request by jduerholt**
In our pipelines, we are currently always installing torch including nvidia drivers and GPU support, which is not needed. For this reason, I changed it to install only the cpu version.

### CODE REVIEW

**Comment by bertiqwerty** [comment]
I stumbled across the same problem. Why did you close this?

**Comment by WaStCo** [comment]
In a discussion with @bertiqwerty , stumbled upon the same thing.

I think the test was dropped because we used:

```console
pip install torch --index-url https://download.pytorch.org/whl/cpu
```

But I think we only need to add an extra index to pip.

```console
pip install torch --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu
```

Where I am unsure about, torch will also be found in the original index, since we do not further specify the version to a point where it is unique (name:version unique to the CPU only index). Thus, this might still fail.

**Comment by jduerholt** [comment]
> I stumbled across the same problem. Why did you close this?

I do not know anymore. I think the speedup in the tests was kind of neglectable ...

**Comment by bertiqwerty** [comment]
The main advantage would not be the pipeline but that users do not have to install as much in the default setting.

**Pull request closed without merging**
