### PR TITLE
Fix NumberOfExperimentsCondition

### PR DESCRIPTION
**Pull request by chrihaas**
Fix condition, by shifting the conditional state by one.

In a stepwise strategy, the next step should be reached if n_experiments_step = n_experiments_available.

### CODE REVIEW

**Review by jduerholt — APPROVED** [review]
Thank you Christian.

**Comment by jduerholt** [comment]
@bertiqwerty: also fine for you?

**Comment by bertiqwerty** [comment]
Hmm... There might be some places in our code where we relied on the old behavior, I think. But in principle, I agree with the change. So let's merge it and we fix our code.

**Review by bertiqwerty — APPROVED** [review]
Thanks, Christian.

**Comment by jduerholt** [comment]
> Hmm... There might be some places in our code where we relied on the old behavior, I think. But in principle, I agree with the change. So let's merge it and we fix our code.

Same for us ;) But we will also fix it.

**Pull request merged**
