### PR TITLE
implement batch constraint for doe

### PR DESCRIPTION
**Pull request by KappatC**

### CODE REVIEW

**Comment by jduerholt** [comment]
@Osburg did the same here: https://github.com/experimental-design/bofire/pull/322

So with which solution should we go on?

**Comment by KappatC** [comment]
A

> @Osburg did the same here: #322
> 
> So with which solution should we go on?

Oh I did not see that one. Sorry, I thought we agreed we would do the doe constraint after you do the polytope sampler and interpoint constraint, but I might as well missunderstood that. Anyways, I am fine with proceeding with Aaron's implementation, since I am still playing around with a formating that would make pyright and black to not complain.

**Comment by Osburg** [comment]
@KappatC Ah, yes this is possible. Sorry in that case! Was working on the batch constraints this weekend anyways and just continued bc I was already on it...

**Comment by jduerholt** [comment]
So, we close this PR and go forward with the one from @Osburg?

**Comment by KappatC** [comment]
@jduerholt sure, let me play a bit around it first and then I ll close it

**Comment by Osburg** [comment]
> @Osburg nw, thanks for working on this in any case. Maybe in the future we just try to coordinate a bit better, so that we don't do duplicate work
yes, sure, this was my bad! Will watch out better next time!

**Pull request closed without merging**
