### PR TITLE
Random search with nonlinear inequality constraints

### PR DESCRIPTION
**Pull request by bertiqwerty**
The data model was missing the nonlinear inequality constraint

### CODE REVIEW

**Comment by jduerholt** [comment]
Just a side node, the `UniversalSampler` is also able to deal with NonlinearConstraints, maybe we should also integrate this one into the RandomStrategy. What do you think?

**Comment by bertiqwerty** [comment]
> Just a side node, the UniversalSampler is also able to deal with NonlinearConstraints, maybe we should also integrate this one into the RandomStrategy. What do you think?

What is the use case?

**Review by jduerholt — APPROVED** [review]
Looks good to me. Thx!

**Comment by bertiqwerty** [comment]
> > What is the use case?
> 
> It uses the Spacefilling criterion from the DoE package, as it is not fitting to the DoE Strategy, Aron made a seperate strategy for it.

Could also be part of Random. Would be easier to find, I guess.

**Comment by jduerholt** [comment]
> Could also be part of Random. Would be easier to find, I guess.

Will keep it in mind, when I refactor random and the samplers in the next weeks.

**Pull request merged**
