### PR TITLE
moved sklearn dependency out of install_requires

### PR DESCRIPTION
**Pull request by bertiqwerty**
#186

### CODE REVIEW

**Comment by bertiqwerty** [comment]
Does anyone know, why the test-pipeline is not triggered?

**Comment by bertiqwerty** [comment]
> Does anyone know, why the test-pipeline is not triggered?

Never mind, typo in the yaml.

**Comment by jduerholt** [comment]
I think our tests are not yet modular enough to run them independet for the different installation modi ...

**Comment by jduerholt** [comment]
And perhaps we should have the different tests configs in different jobs in the pipeline so that one sees directly in the PR where it crashes.

**Comment by bertiqwerty** [comment]
I have safeguarded the hell out of the tests. Can you have another look, @jduerholt .

**Comment by jduerholt** [comment]
Looks good to me, only one thing which came to my mind:

In the minimal test plan we should also run the following other test files:

- data_models/test_base.py
- data_models/test_constraint_fulfillment.py
- data_models/test_constrints.py
- data_models/domain_validators.py
- data_models/test_features.py
- data_models/test_filters.py
- data_models/test_nchoosek_combinatorics.py
- data_models/test_numeric.py
- data_models/test_unions.py
- data_models/test_util.py

**Comment by bertiqwerty** [comment]
Ok, @jduerholt, I have added more tests.

**Comment by jduerholt** [comment]
Thanks, thats looks perfect. One last thing which came to my mind: we should also add the `cloudpickle` dependency to `optimization`. We use it to store/save empirical surrogates which cannot be pickled. Currently, the tests are not executed as these tests are safeguarded. I will approve now, than you can merge it in without the need to wait for me.

**Review by jduerholt — APPROVED** [review]

**Pull request merged**
